.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pif-config-systems-add 1  "pif-config-systems-add " 
.SH NAME
pif\-config\-systems\-add \- Add one or more systems to the existing filter
.SH SYNOPSIS
\fBpif\-config\-systems\-add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISYSTEM\fR> 
.SH DESCRIPTION
Add one or more systems to the existing filter
.PP
Appends to the current filter without removing existing entries.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fISYSTEM\fR>
System names to include (e.g. tads3 inform6 inform)
