.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pif-config-verbose-reset 1  "pif-config-verbose-reset " 
.SH NAME
pif\-config\-verbose\-reset \- Reset the verbosity level to the built\-in default (2)
.SH SYNOPSIS
\fBpif\-config\-verbose\-reset\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Reset the verbosity level to the built\-in default (2)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
