.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pif-config-systems-reset 1  "pif-config-systems-reset " 
.SH NAME
pif\-config\-systems\-reset \- Remove the entire systems filter
.SH SYNOPSIS
\fBpif\-config\-systems\-reset\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove the entire systems filter
.PP
After reset, Auto mode considers all known IF systems again.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
