.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pif-registry-list 1  "pif-registry-list " 
.SH NAME
pif\-registry\-list \- Print all recorded extension installations
.SH SYNOPSIS
\fBpif\-registry\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print all recorded extension installations
.PP
Shows the name, installed version, and on\-disk path for every extension that pif has installed on this machine.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
