.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pif-config-show 1  "pif-config-show " 
.SH NAME
pif\-config\-show \- Display the current config file with syntax highlighting
.SH SYNOPSIS
\fBpif\-config\-show\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display the current config file with syntax highlighting
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
